# Generated by Django 2.1.7 on 2019-02-23 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='password',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='user_ip',
            field=models.GenericIPAddressField(blank=True, null=True, unique=True),
        ),
    ]
